name: Deploy Node.js API
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install express axios
    - run: node index.js &
    - uses: actions/upload-artifact@v2
      with:
        name: api
        path: .
