- name: Idenfit login endpointine POST isteği gönderiliyor
  run: |
    curl -i -X POST "https://integration.idenfit.com/login" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "username=zehraauludag@gmail.com&password=Zehra.1992" > full_response.txt

- name: full_response.txt içeriğini göster
  run: cat full_response.txt
