name: Get Idenfit Token and Send to Logic Apps

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  # 15 dakikada 1 otomatik tetikleme

jobs:
  get-token:
    runs-on: ubuntu-latest

    steps:
      - name: Idenfit login endpointine POST isteği gönderiliyor
        id: get_token
        run: |
          RESPONSE_HEADERS=$(curl -s -D - -o /dev/null -X POST "https://integration.idenfit.com/login" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "username=zehraauludag@gmail.com&password=Zehra.1992")

          echo "Tüm Headerlar:"
          echo "$RESPONSE_HEADERS"

          TOKEN=$(echo "$RESPONSE_HEADERS" | grep -i "^refresh-token:" | awk '{print $2}' | tr -d '\r')

          echo "Bulunan Token: $TOKEN"

          echo "::set-output name=token::$TOKEN"

      - name: Token'ı Logic Apps URL'sine POST et
        run: |
          LOGIC_APPS_URL="https://prod-105.westeurope.logic.azure.com:443/workflows/eeba067314d9496993368d8d9df81730/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=ddjnu7xuAqnFuweilT_exxHGT4tDNJd4Xkh5Ua-oh5c"

          curl -X POST "$LOGIC_APPS_URL" \
            -H "Content-Type: application/json" \
            -d "{\"token\":\"${{ steps.get_token.outputs.token }}\"}"

          echo "Token Logic Apps URL'sine gönderildi."
