
on:
  workflow_dispatch:

jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - name: Idenfit login endpointine POST isteği gönderiliyor
        id: login
        run: |
          RESPONSE=$(curl -s -D - -o /dev/null -X POST "https://integration.idenfit.com/login" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "username=zehraauludag@gmail.com&password=Zehra.1992")

          TOKEN=$(echo "$RESPONSE" | grep -i "authorization:" | cut -d' ' -f2-)
          
          echo "Authorization header değeri (logda gizlenebilir): $TOKEN"

          echo "$TOKEN" > token.txt

      - name: Token dosyasını oku ve göster
        run: |
          echo "token.txt içeriği aşağıda:"
          cat token.txt
