name: call-api

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Idenfit login endpoint and extract token from headers
        run: |
          echo "Calling Idenfit login endpoint with POST..."

          RESPONSE=$(curl -s -D - -o /dev/null -X POST "https://integration.idenfit.com/login" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "username=zehraauludag@gmail.com&password=Zehra.1992")

          echo "Full Response Headers:"
          echo "$RESPONSE"

          TOKEN=$(echo "$RESPONSE" | grep -i "Authorization:" | awk '{print $2}')

          echo "Parsed Token:"
          echo "$TOKEN"
