name: Idenfit Token Generator

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install jq

      - name: Get Token from Idenfit
        run: |
          echo "Calling Idenfit login endpoint..."
          RESPONSE=$(curl -s "https://integration.idenfit.com/login?username=zehraauludag@gmail.com&password=Zehra.1992")
          echo "Full Response:"
          echo "$RESPONSE"
          echo "Parsed Token:"
          echo "$RESPONSE" | jq -r '.token'
