const express = require("express");
const axios = require("axios");

const app = express();
let currentToken = null;

async function refreshToken() {
  try {
    const response = await axios.post(
      "https://integration.idenfit.com/login?username=zehraauludag@gmail.com&password=Zehra.1992",
      null,
      {
        headers: {
          "content-type": "application/x-www-form-urlencoded",
          from: "mobile",
        },
      },
    );
    // Token header içinde olabilir, farklı isimleri kontrol et
    currentToken =
      response.headers["x-auth-token"] ||
      response.headers["token"] ||
      response.headers["authorization"];

    console.log("Token refreshed:", currentToken);
  } catch (error) {
    console.error("Token refresh error:", error.message);
  }
}

// Uygulama açılır açılmaz token yenile
refreshToken();

// Her 10 dakikada (600000 ms) bir token yenile
setInterval(refreshToken, 600000);

// /token endpoint'i token bilgisini JSON olarak döner
app.get("/token", (req, res) => {
  if (currentToken) {
    res.json({ token: currentToken });
  } else {
    res.status(503).json({ error: "Token not available yet" });
  }
});

// Port ayarı (Replit ve benzeri ortamlar için port'u env'den al)
const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});
